/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.catvod.dome;
import android.content.Context;
import com.github.catvod.spider.Jable;


public class App {

    public static void main(String[] args) {
        Jable jav = new Jable();
        String str_extend = "http://ys.qtw.asia/lvdou_api.php/v1.vod";
        //筛选开关
        boolean filter_switch = true;
        //筛选类型的第几个的下标(如:类型，地区，语言，年份....)
        int filter_type_index=1;
        //测试筛选的下标
        int filter_num_index=1;
        //搜索开关
        boolean search_switch = false;
        //搜索关键字
        String search_keyword = "汪汪";
        //测试的类型的下标,从0开始(电影,电视剧...)
        int test_type_index = 0;
        //测试category的页数,从1开始
        int test_category_page = 1;
        //测试的视频下标，从0开始
        int test_vod_index =2;
        //测试视频源的下标,从0开始
        int test_vod_from_index = 0;

        String className = jav.getClass().getName();
        String spiderName = className.substring(className.lastIndexOf('.') + 1);
        System.out.println("你测试的类是--->"+spiderName); // 输出 "Object"
        try {
            jav.init(new Context(),str_extend);
        } catch (Exception e) {
            // TODO: handle exception
        }
    }
}
